version: '3'
volumes:
  pgkc:
services:
  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
      - pgkc:/var/lib/postgresql/data
    environment:
      SA_PASSWORD: p0ssW0rD
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
  kc:
    image: registry.access.redhat.com/redhat-sso-7/sso73-openshift
    volumes:
      - ./container/modules/system/layers/base/com/microsoft/sqlserver/main/:/opt/eap/modules/system/layers/base/com/microsoft/sqlserver/main/
      - ./container/configuration/standalone-openshift.xml:/opt/eap/standalone/configuration/standalone-openshift.xml
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: sqlserver
      DB_PORT: 1433
      DB_DATABASE: master
      DB_SCHEMA: guest
      DB_USER: SA
      DB_PASSWORD: p0ssW0rD
      SSO_ADMIN_USERNAME: admin
      SSO_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
      - 9990:9990
    depends_on:
      - sqlserver
